

name: UI Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Google Chrome
        uses: actions/download-artifact@v4

      - run: |

              sudo apt-get upgrade google-chrome-stable -y
              mvn clean test

      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1

#