

name: Smoke Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven
      - name: Set up Chrome browser
      - uses: browser-actions/setup-chrome@v1
        with:
            options: |
              --disable-dev-shm-usage
              --ignore-ssl-errors=yes
              --ignore-certificate-errors
              --no-sandbox
              --headless
        run: google-chrome-stable --version
      - name: Build with Maven
        run: mvn clean test
