

name: Smoke Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - uses: actions/download-artifact@v4
      - with:
        name: dist
      - uses: ./
        run: |
            firefox --version
      - uses: ./
        with:
          firefox-version: latest-esr
      - run: |
          firefox --version
      - uses: ./
        with:
              firefox-version: "132.0"
      - run: |
          firefox --version
      - uses: ./
        with:
                firefox-version: "devedition-132.0b1"
      - run: |
             firefox --version

#          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: Build with Maven
        run: mvn clean test
