

name: Smoke Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean test

#      - name: Run Chrome
#        uses: actions/download-artifact@v4
#        with:
#            # Optional: do not specify to match Chrome's version
#            chromedriver-version: '88.0.4324.96'
#            options:
#              addArguments--remote-debugging-port=9222

#        run: chromedriver --url-base=/wd/hub
#        run: apt-get install -y ./google-chrome-stable_current_amd64.deb
#             google-chrome --version


      #          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
#      - name: Build with Maven
#        run: _JAVA_OPTIONS=-Djdk.net.URLClassPath.disableClassPathURLCheck=true mvn clean compile package #_JAVA_OPTIONS=-Djdk.net.URLClassPath.disableClassPathURLCheck=true
#
